WordCount/WordCount/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

WordCount/main/urls.py
from django.conf.urls import url
from . import views

app_name='main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^more/sites$', views.moresites, name='sites'),
    url(r'^more/sites/Add/$', views.addSite, name='add'),
    url(r'^more/results$', views.more, name='more'),
]

WordCount/main/models.py
from django.db import models

class Word(models.Model):
    word = models.CharField( max_length=200, primary_key=True )
    gender = models.CharField( max_length=1, null=True, blank=True )

    def __str__(self):
        return u'%s %s' % (self.word, self.gender)

    #TODO add tests
    #Test for adding genders
    def start(self, url):
        from lxml import html
        from urllib.parse import urljoin
        import requests

        headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

        page = requests.get( url=url, headers=headers )
        tree = html.fromstring(page.content.decode("utf-8"))

        links = tree.get_element_by_id("letters").iterlinks()

        for link in links:
            url = urljoin(url, link[2])

            page = requests.get(url=url, headers=headers)
            tree = html.fromstring(page.content.decode("utf-8"))

            elements = tree.get_element_by_id("ranges")[0]

            for option in elements:
                url = urljoin(url, option.attrib["value"])

                page = requests.get(url=url, headers=headers)
                tree = html.fromstring(page.content.decode("utf-8"))

                words = tree.get_element_by_id("lexems").iterlinks()

                for word in words:
                    url = urljoin(url, word[2])

                    page = requests.get(url=url, headers=headers)
                    tree = html.fromstring(page.content.decode("utf-8"))

                    lex = tree.xpath('//*[@id="main_content"]/h2/span[1]')[0].text_content()

                    types = None

                    if len(tree.find_class("grammar")) != 0:
                        types = tree.find_class("grammar")[0].text_content().split(':')[1]

                    english = None

                    if len(tree.find_class("eng")) != 0:
                        english = tree.find_class("eng")

                    self.addWords(lex, types.lower(), english)

    def addWords(self, word, types, english):
        types = types.split(',')

        w = Word()
        w.word = word.lower()

        for element in types:
            if "машки род" in element:
                w.gender = 'm'
                types.remove( element )
            elif "женски род" in element:
                w.gender = 'f'
                types.remove( element )
            elif "среден род" in element:
                w.gender = 'n'
                types.remove( element )

        w.save()

        if english is not None:
            for e in english:
                eng = EnglishWord()
                eng.word = w
                eng.english = e.text_content().split()[1].lower()
                eng.save()

        if type is not None:
            for element in types:
                if "свршен" in element and "несвршен" in element:
                    self.addType(w, "свршен")
                    self.addType(w, "несвршен")
                else:
                    self.addType(w, element.strip())

    def addType(self, word, wordtype):
        type = Type()
        type.word = word
        type.word_type = wordtype
        type.save()


class Type(models.Model):
    #id by default
    word = models.ForeignKey( 'Word', on_delete=models.CASCADE)
    word_type = models.CharField( max_length=200 )

    def __str__(self):
        return u'%s %s' % (self.word, self.word_type)

class EnglishWord(models.Model):
    #id by default
    word = models.ForeignKey('Word', on_delete=models.CASCADE)
    english = models.CharField(max_length=200)

    def __str__(self):
        return u'%s %s' % (self.word, self.english)

class Name(models.Model):
    name = models.CharField( max_length=200, primary_key=True )
    gender = models.CharField( max_length=1 )

    visited = []

    def __str__(self):
        return u'%s %s' % (self.name, self.gender)

    #TODO test if Зорица is in the database
    def start(self, url):
        self.purgeVisited()
        self.addNames(url)

    def purgeVisited(self):
        self.visited = []

    def addNames(self, url):
        from lxml import html
        from urllib.parse import urljoin
        import requests

        self.visited.append(url)

        page = requests.get( url=url )
        tree = html.fromstring(page.content)

        names = tree.cssselect('body > div.body-wrapper > div > table > tr:nth-child(2) > td:nth-child(1) > div > div')

        i = 0

        #TODO test
        for element in names:
            if i < 5:
                i += 1
                continue
            names = element.text_content().split()
            if "(" in names[1]:
                del names[1]
            name = Name()
            name.name = names[1].lower()
            if "m" in names and "f" in names:
                name.gender = 'u'
            elif "m" in names:
                name.gender = 'm'
            else:
                name.gender = 'f'
            name.save()

        a = tree.xpath('/html/body/div[2]/div/table/tr[2]/td[1]/div/center/a/@href')

        site = urljoin(url, a[0])

        if site in self.visited:
            self.visited = []
            return

        return self.addNames(site)

class Site(models.Model):
    site = models.URLField( primary_key=True )
    checked_date = models.DateTimeField( 'date checked', null=True, blank=True)

    #TODO save

    def __str__(self):
        return u'%s %s' % (self.site, self.checked_date)

class WordSoup(models.Model):
    #id by default
    word = models.ForeignKey( 'Word', on_delete=models.CASCADE )
    site = models.ForeignKey( 'Site', on_delete=models.CASCADE )
    count = models.IntegerField( default=0 )

    def __str__(self):
        return u'%s %s %d' % (self.word.word, self.site.site, self.count)

class NameSoup(models.Model):
    #id by default
    name = models.ForeignKey( 'Name', on_delete=models.CASCADE)
    site = models.ForeignKey( 'Site', on_delete=models.CASCADE)
    count = models.IntegerField( default=0 )

    def __str__(self):
        return u'%s %s %d' % (self.name.name, self.site.site, self.count)

WordCount/main/views.py
from django.db.models.aggregates import Sum
from django.db.models import Q
from django.http.response import HttpResponse
from django.shortcuts import render
from requests.exceptions import MissingSchema

from main.models import *

# Create your views here.
def index(request):

    sites = Site.objects.all().values('site')[:17]

    if request.GET.get('q', '') != '':
        if request.GET.get('q', '') not in sites:
            from itertools import chain
            sites = list( chain( sites, Site.objects.filter(site=request.GET.get('q', '') ) ) )

    context = {
        'sites': sites,
    }

    if 'button' in request.POST:
        context['order'] = request.POST['order']
        context['type'] = request.POST['type']
        context['web'] = request.POST['site']

        if 'genderword' in request.POST:
            context['genderword'] = request.POST['genderword']
        if 'gender' in request.POST:
            context['gender'] = request.POST['gender']

        if request.POST['type'] == 'name':
            return Results(
                context,
                request,
                request.POST['order'],
                request.POST['type'],
                request.POST['site'],
                request.POST['gender'])
        if request.POST['type'] == 'именка':
            return Results(
                context,
                request,
                request.POST['order'],
                request.POST['type'],
                request.POST['site'],
                request.POST['genderword'])
        else:
            return Results(context, request, request.POST['order'], request.POST['type'], request.POST['site'])

    return render(request, 'main/index.html', context=context)

def Results(context, request, ordering, type, site, gender=None, url='main/index.html', splice=True):

    order = '-'
    if ordering == 'least':
        order = ''

    try:

        words = None
        if type == 'name':
            words = returnNames(gender, site, order, splice=True)
        else:
            if type == 'именка':
                words = returnWords(site, type, order, gender, splice=True)
            else:
                words = returnWords(site, type, order, splice=True)

        if len(words) == 0:
            words = ['Нема Резултати']

        context['results'] = words

        return render(request, url, context=context)
    except (NameSoup.DoesNotExist, WordSoup.DoesNotExist):
        pass

def moresites( request ):
    sites = Site.objects.all().values('site')

    context = {
        'sites': sites,
    }

    return render(request, 'main/moresites.html', context=context)

def addSite( request ):

    context = {

    }

    if 'submit' in request.POST:
        if len(request.POST) != 0:
            import requests

            headers = {
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

            try:

                page = requests.get(url=request.POST['site'], headers=headers)

                if page.status_code == 200:
                    Site.objects.create(site=request.POST['site'])
                else:
                    context['error'] = 1
            except Exception:
                context['error'] = 1

    return render(request, 'main/addSite.html', context)

def returnNames(gender, site, order, splice=True):
    if gender == 'u':
        if site == 'all':
            if splice is not True:
                return NameSoup.objects.filter(name__gender='u').values('name', 'name__gender').annotate(
                    count=Sum('count')).order_by(order + 'count')
            return NameSoup.objects.filter(name__gender='u').values('name', 'name__gender').annotate(count = Sum('count') ).order_by(order + 'count')[:17]
        else:
            if splice is not True:
                return NameSoup.objects.filter(name__gender='u', site__site=site).order_by(order + 'count')
            return NameSoup.objects.filter(name__gender='u', site__site=site).order_by(order + 'count')[:17]
    elif gender == 'm':
        if site == 'all':
            if splice is not True:
                return NameSoup.objects.filter(name__gender='m').values('name', 'name__gender').annotate(
                    count=Sum('count')).order_by(order + 'count')
            return NameSoup.objects.filter(name__gender='m').values('name', 'name__gender').annotate(count = Sum('count') ).order_by(order + 'count')[:17]
        else:
            if splice is not True:
                return NameSoup.objects.filter(name__gender='m', site__site=site).order_by(order + 'count')
            return NameSoup.objects.filter(name__gender='m', site__site=site).order_by(order + 'count')[:17]
    else:
        if site == 'all':
            if splice is not True:
                return NameSoup.objects.filter(name__gender='f').values('name', 'name__gender').annotate(
                    count=Sum('count')).order_by(order + 'count')
            return NameSoup.objects.filter(name__gender='f').values('name', 'name__gender').annotate(count = Sum('count') ).order_by(order + 'count')[:17]
        else:
            if splice is not True:
                return NameSoup.objects.filter(name__gender='f', site__site=site).order_by(order + 'count')
            return NameSoup.objects.filter(name__gender='f', site__site=site).order_by(order + 'count')[:17]

def returnWords( site, type, order, gender=None, splice=True):
    from django.db import connection
    if gender is not None:
        if gender == 'e':
            if site == 'all':
                if splice is not True:
                    return WordSoup.objects.filter(word__gender__in=['m', 'f', 'n']).values('word', 'word__type',
                                                                                            'word__gender').annotate(
                        count=Sum('count')).order_by(order + 'count')
                return WordSoup.objects.filter(word__gender__in=['m', 'f', 'n']).values('word', 'word__type', 'word__gender').annotate(count = Sum('count') ).order_by(order + 'count')[:17]
            else:
                if splice is not True:
                    return WordSoup.objects.filter(word__gender__in=['m', 'f', 'n'], site__site=site).order_by(
                        order + 'count')
                return WordSoup.objects.filter(word__gender__in=['m', 'f', 'n'], site__site=site).order_by(order + 'count')[:17]
        elif gender == 'm':
            if site == 'all':
                if splice is not True:
                    return WordSoup.objects.filter(word__gender='m').values('word', 'word__type', 'word__gender') \
                               .annotate(count=Sum('count')).order_by(order + 'count')
                return WordSoup.objects.filter(word__gender='m').values('word', 'word__type', 'word__gender')\
                           .annotate(count = Sum('count') ).order_by(order + 'count')[:17]
            else:
                if splice is not True:
                    return WordSoup.objects.filter(word__gender='m', site__site=site).order_by(order + 'count')
                return WordSoup.objects.filter(word__gender='m', site__site=site).order_by(order + 'count')[:17]
        elif gender == 'f':
            if site == 'all':
                if splice is not True:
                    return WordSoup.objects.filter(word__gender='f').values('word', 'word__type', 'word__gender') \
                               .annotate(count=Sum('count')).order_by(order + 'count')
                return WordSoup.objects.filter(word__gender='f').values('word', 'word__type', 'word__gender')\
                           .annotate(count = Sum('count') ).order_by(order + 'count')[:17]
            else:
                if splice is not True:
                    return WordSoup.objects.filter(word__gender='f', site__site=site).order_by(order + 'count')
                return WordSoup.objects.filter(word__gender='f', site__site=site).order_by(order + 'count')[:17]
        else:
            if site == 'all':
                if splice is not True:
                    return WordSoup.objects.filter(word__gender='n').values('word', 'word__type', 'word__gender') \
                               .annotate(count=Sum('count')).order_by(order + 'count')
                return WordSoup.objects.filter(word__gender='n').values('word', 'word__type', 'word__gender')\
                           .annotate(count = Sum('count')).order_by(order + 'count')[:17]
            else:
                if splice is not True:
                    return WordSoup.objects.filter(word__gender='n', site__site=site).order_by(order + 'count')
                return WordSoup.objects.filter(word__gender='n', site__site=site).order_by(order + 'count')[:17]
    else:
        if site == 'all':
            with connection.cursor() as cursor:
                if order == '-':
                    cursor.execute(
                        "SELECT word_type, SUM(count) FROM main_wordsoup JOIN main_type USING (word_id) GROUP BY word_type ORDER BY count")
                else:
                    cursor.execute(
                        "SELECT word_type, SUM(count) FROM main_wordsoup JOIN main_type USING (word_id) GROUP BY word_type ORDER BY -count")

                if splice is not True:
                    return cursor.fetchall()
                return cursor.fetchall()[:17]
        else:
            with connection.cursor() as cursor:
                if order == '-':
                    cursor.execute(
                        "SELECT word_type, site_id, SUM(count) FROM main_wordsoup JOIN main_type USING (word_id) WHERE site_id=%s GROUP BY word_type ORDER BY -count",
                    [site])
                else:
                    cursor.execute(
                        "SELECT word_type, site_id, SUM(count) FROM main_wordsoup JOIN main_type USING (word_id) WHERE site_id=%s GROUP BY word_type ORDER BY count",

WordCount/main/templates/main/addSite.html
{% extends 'main/template.html' %}

{% block title %}
    Add Site
{% endblock %}

{% block content %}
    <h2><a href="{% url 'main:index' %}"><span class="glyphicon glyphicon-menu-left"></span></a>Додади Нов Вебсајт</h2>
    {% if error %}
        <h5>Сајтот не е валиден</h5>
    {% endif %}
    <form action="#" method="POST">
        {% csrf_token %}
        <input id="site" name="site" type="text" placeholder="Внеси валиден вебсајт">
        <button id="submit" value="submit" name="submit" type="submit" class="btn btn-link"><span class="glyphicon glyphicon-send"></span></button>
    </form>
{% endblock %}

WordCount/main/templates/main/index.html
{% extends 'main/template.html' %}

{% block content %}
    <div>
    <div class="col-md-12 buttons-container">
        <form action="#" method="post">
            {% csrf_token %}
            <h2>Прикажи ги
            <select id="order" name="order">
                <option value="most"
                {% if order == 'most' %}
                        selected
                {% elif not order %}
                        seleceted
                {% endif %}
                >највеќе</option>
                <option value="least"
                {% if order == 'least' %}
                            selected
                {% endif %}
                >најмалку</option>
            </select>
            бараните
            <select id="type" name="type">

                <option value="name"
                {% if type == 'name' %}
                        selected
                {% elif not type %}
                        seleceted
                {% endif %}
                >имиња</option>

                <option value="именка"
                {% if type == 'именка' %}
                        selected
                {% endif %}
                >именки</option>

                <option value="друго"
                {% if type == 'друго' %}
                        selected
                {% endif %}
                >видови зборови</option>

            </select>
            <div id="g">
            од
            <select id="genderword" name="genderword">
                <option value="e"
                        {% if genderword == 'e' %}
                            selected
                        {% endif %}
                >секој</option>
                <option value="m"
                {% if genderword == 'm' %}
                            selected
                {% endif %}
                >машки</option>
                <option value="f"
                {% if genderword == 'f' %}
                            selected
                {% endif %}
                >женски</option>
                <option value="n"
                {% if genderword == 'n' %}
                            selected
                {% endif %}
                >среден</option>
            </select>
            род
            </div>
            <div id="gname">
                со
                <select id="gender" name="gender">
                    <option value="u"
                    {% if gender == 'u' %}
                            selected
                    {% endif %}
                    >унисекс</option>
                    <option value="m"
                    {% if gender == 'm' %}
                            selected
                    {% endif %}
                    >машко</option>
                    <option value="f"
                    {% if gender == 'f' %}
                            selected
                    {% endif %}
                    >женско</option>
                </select>
                име
            </div>
            од
            <select id="site" name="site">
                <option value="all"
                {% if web == 'all' %}
                            selected
                {% endif %}
                >сите сајтови</option>
                    {% if sites %}

                        {% for site in sites %}

                            <option value="{{ site.site }}"
                            {% if web == site.site %}
                            selected
                            {% endif %}
                            >{{ site.site }}</option>

                        {% endfor %}

                    {% endif %}
                <option value="more">повеќе</option>
            </select>
                <button type="submit" class="btn btn-link" value="submit" name="button">
                    <span class="glyphicon glyphicon-menu-right"></span>
                </button>
            </h2>
            </form>
    </div>
    </div>

    <div class="content">

        <ul>
            {% for result in results %}
                {% if result == 'Нема Резултати' %}
                    <li>{{ result }}</li>
                {% elif type == 'именка' %}
                    <li> {{ result.word }} {{ result.site.site }} {{ result.count }} </li>
                {% elif type == 'name'%}
                    <li> {{ result.name }} {{ result.site.site }} {{ result.count }}</li>
                {% else %}
                    <li> {{ result.0 }} {{ result.1 }} {{ result.2 }} </li>
                {% endif %}
            {% endfor %}
            {% if results|length > 15 %}

                <a id="more" name="more" href="{% url 'main:more' %}?{% if order %}order={{ order }}{% endif %}{% if type %}&type={{ type }}{% endif %}{% if genderword %}&genderword={{ genderword }}{% endif %}{% if gender %}&gender={{ gender }}{% endif %}{% if web %}&web={{ web }}{% endif %}">Види повеќе резултати</a>

            {% endif %}
        </ul>

    </div>

    <script>
        $(document).ready(function(){
            $('#type').change(function(){
                $('#g')[$(this).val()=='именка' ? 'show' : 'hide']();
        }).trigger('change');
    });
         $(document).ready(function(){
            $('#type').change(function(){
                $('#gname')[$(this).val()=='name' ? 'show' : 'hide']();
        }).trigger('change');
    });
         $(document).ready(function () {
           $("#site").change(function () {
             if ($(this).val() == 'more')
             {
                 window.location.href = 'more/sites'
             }
         }).trigger('change');
     });
    </script>
{% endblock %}

WordCount/main/templates/main/moreresults.html
{% extends 'main/template.html' %}

{% block title %}
    More Results
{% endblock %}

{% block content %}
    <div>
        <h2><a href="{% url 'main:index' %}"><span class="glyphicon glyphicon-menu-left"></span></a></h2><h2>Повеќе Резултати</h2>
        <ul>
            {% for result in results %}
                {% if type == 'именка' %}
                    <li> {{ result.word }} {{ result.site.site }} {{ result.count }} </li>
                {% elif type == 'name'%}
                    <li> {{ result.name }} {{ result.site.site }} {{ result.count }}</li>
                {% else %}
                    <li> {{ result }} </li>
                {% endif %}
            {% endfor %}
        </ul>

    </div>
{% endblock %}

WordCount/main/templates/main/moresites.html
{% extends 'main/template.html' %}

{% block title %}
    Sites
{% endblock %}

{% block content %}

    <div>
        <h2>Избери друг сајт</h2>
        <ul>
            {% for site in sites %}

                <li><a href="/?q={{ site }}">{{ site }}</a></li>

            {% endfor %}
            <li>
            <a href="{% url 'main:add' %}">Додади нов сајт</a>
            </li>
        </ul>
    </div>

{% endblock %}

WordCount/main/templates/main/result.html
{% extends 'main/template.html' %}

WordCount/main/templates/main/template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/template.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
    <div class="middle">
    {% block content %}
    {% endblock %}
    </div>
    </div>
</body>
</html>